updated automatic measure creation function
qlik-oss/qwik-trellis pull request #41
Opened 2019-09-27 10:17 UTC by rileymd88

Updated the function to prevent some cases where an incorrect formula was being created

2019-11-26 18:11 UTC, AlexTimo commented
Will this be reviewed anytime soon? There is a number of problems with the extension that I've outlined [here](https://community.qlik.com/t5/Qlik-Sense-Integration/Problems-with-Trellis-extension/m-p/1646333#M11767), I suspect this PR might deal with some of those.

2020-01-23 10:42 UTC, dev-abhirn approved these changes

2020-02-27 20:10 UTC, PurwaShrivastava approved these changes

2020-02-28 09:38 UTC, PurwaShrivastava requested changes
This needs to be tested for Advanced mode and two dimension support, so cannot be merged before a thorough testing.

2020-06-02 08:17 UTC, PurwaShrivastava approved these changes
Have fixed the issues with Two Dimensions and Advanced Mode. Has been also manually tested and verified. Merging it to MAster now.

2020-06-02 08:17 UTC, merged